"use client"

import * as React from "react"
import { AppSidebar } from "@/components/app-sidebar"
import { SiteHeader } from "@/components/site-header"
import {
  SidebarInset,
  SidebarProvider,
} from "@/components/ui/sidebar"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"

const reports = [
  { id: 1, title: "Aurum Pit‑3 — Monthly Sustainability Report", date: "2025-07-31", author: "EcoSync AI", status: "Published", summary: "Live LCA snapshot with circular routing outcomes." },
  { id: 2, title: "Water Balance & Reuse — Q2 Summary", date: "2025-06-30", author: "EcoSync AI", status: "Published", summary: "Reclaim improvements and discharge compliance log." },
  { id: 3, title: "Emissions Intensity Benchmark — H1", date: "2025-06-15", author: "EcoSync AI", status: "Published", summary: "CO₂ intensity by stage with mitigation actions." },
  { id: 4, title: "Waste-to-Value Routing — Weekly", date: "2025-08-07", author: "EcoSync AI", status: "Draft", summary: "Aggregates, paste backfill, brick feed and SCM streams." },
]

export default function Page() {
  return (
    <SidebarProvider style={{ "--sidebar-width": "calc(var(--spacing) * 72)", "--header-height": "calc(var(--spacing) * 12)" }}>
      <AppSidebar variant="inset" />
      <SidebarInset>
        <SiteHeader />
        <div className="flex flex-1 flex-col">
          <div className="@container/main flex flex-1 flex-col gap-2">
            <div className="flex flex-col gap-4 py-4 md:gap-6 md:py-6 px-4 lg:px-6">
              <Card>
                <CardHeader>
                  <CardTitle>Your Reports</CardTitle>
                  <CardDescription>Auto-generated by EcoSync — exportable and audit-ready</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="overflow-hidden rounded-lg border">
                    <ul className="divide-y">
                      {reports.map((r) => (
                        <li key={r.id} className="flex items-center justify-between gap-4 p-4 hover:bg-muted/30">
                          <div className="flex min-w-0 flex-col">
                            <div className="flex items-center gap-2">
                              <span className="truncate text-sm font-medium">{r.title}</span>
                              <Badge variant="outline" className="text-muted-foreground">{r.status}</Badge>
                            </div>
                            <div className="truncate text-xs text-muted-foreground">{r.summary}</div>
                          </div>
                          <div className="flex shrink-0 flex-col items-end gap-1 text-right">
                            <div className="text-xs text-muted-foreground">{new Date(r.date).toLocaleDateString()}</div>
                            <div className="text-xs text-muted-foreground">{r.author}</div>
                            <div className="flex gap-2">
                              <button className="rounded-md border px-2 py-1 text-xs">Open</button>
                              <button className="rounded-md border px-2 py-1 text-xs">Export</button>
                            </div>
                          </div>
                        </li>
                      ))}
                    </ul>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </SidebarInset>
    </SidebarProvider>
  )
}
